### ISSUE TITLE
Some error.

### ISSUE THREAD

**Issue by JohnMKC** [VeliovGroup/Meteor-Files#128]
Hi there,

I have checked simple upload demo but showing some errors.
```
I20160705-09:37:34.371(5.5)? [FilesCollection] [find({}, undefined)]
```

```
 [FilesCollection] [Abort Method]: m3heeRBmGKJcjJjQ9 - undefined
```

What are these errors ? I'm not able to figure it out :/

**Comment by dr-dimitru** [comment]
> [FilesCollection] [find({}, undefined)]
> [FilesCollection] [Abort Method]: m3heeRBmGKJcjJjQ9 - undefined

Not a errors, just debug logs.
 1. Are you on Windows?
 2. Do you get any Client-Side errors?
 3. Could you post more debug messages, which should be shown before those two lines you've posted?

**Comment by JohnMKC** [comment]
1. Yes, Windows.
2. No. Not on client side.
3. Debug log.
```
I20160705-10:41:18.473(5.5)? [FilesCollection] [serve(assets\app\uploads\Images/ca3nAxcREBSXdaxSG.jpg, original)] [200]
I20160705-10:41:27.777(5.5)? [FilesCollection] [File Start Method] IMG_20160605_215020.jpg - a3tDdoBiqrZv7EMQa
I20160705-10:41:27.777(5.5)? [FilesCollection] [Upload] [Start Method] Got #-1/10 chunks, dst: IMG_20160605_215020.jpg
I20160705-10:41:28.562(5.5)? [FilesCollection] [Upload] [DDP] Got #1/10 chunks, dst: IMG_20160605_215020.jpg
I20160705-10:41:28.709(5.5)? [FilesCollection] [Upload] [DDP] Got #2/10 chunks, dst: IMG_20160605_215020.jpg
I20160705-10:41:28.762(5.5)? [FilesCollection] [Upload] [DDP] Got #3/10 chunks, dst: IMG_20160605_215020.jpg
I20160705-10:41:28.778(5.5)? [FilesCollection] [Upload] [DDP] Got #10/10 chunks, dst: IMG_20160605_215020.jpg
I20160705-10:41:28.909(5.5)? [FilesCollection] [Upload] [DDP] Got #4/10 chunks, dst: IMG_20160605_215020.jpg
I20160705-10:41:29.009(5.5)? [FilesCollection] [Upload] [DDP] Got #5/10 chunks, dst: IMG_20160605_215020.jpg
I20160705-10:41:29.109(5.5)? [FilesCollection] [Upload] [DDP] Got #6/10 chunks, dst: IMG_20160605_215020.jpg
I20160705-10:41:29.194(5.5)? [FilesCollection] [Upload] [DDP] Got #7/10 chunks, dst: IMG_20160605_215020.jpg
I20160705-10:41:29.310(5.5)? [FilesCollection] [Upload] [DDP] Got #8/10 chunks, dst: IMG_20160605_215020.jpg
I20160705-10:41:29.395(5.5)? [FilesCollection] [Upload] [DDP] Got #9/10 chunks, dst: IMG_20160605_215020.jpg
I20160705-10:41:29.426(5.5)? [FilesCollection] [Upload] [DDP] Got #-1/10 chunks, dst: IMG_20160605_215020.jpg
I20160705-10:41:29.426(5.5)? [FilesCollection] [Upload] [finish(ing)Upload] -> assets\app\uploads\Images/a3tDdoBiqrZv7EMQa.jpg
I20160705-10:41:29.426(5.5)? [FilesCollection] [Upload] [finish(ed)Upload] -> assets\app\uploads\Images/a3tDdoBiqrZv7EMQa.jpg
I20160705-10:41:29.448(5.5)? [FilesCollection] [_preCollectionCursor.observeChanges] [removed]: a3tDdoBiqrZv7EMQa
I20160705-10:41:29.467(5.5)? [FilesCollection] [download(/cdn/storage/Images/a3tDdoBiqrZv7EMQa/original/a3tDdoBiqrZv7EMQa.jpg, original)]
I20160705-10:41:29.490(5.5)? [FilesCollection] [serve(assets\app\uploads\Images/a3tDdoBiqrZv7EMQa.jpg, original)] [200]
I20160705-10:41:31.521(5.5)? [FilesCollection] [download(/cdn/storage/Images/a3tDdoBiqrZv7EMQa/original/a3tDdoBiqrZv7EMQa.jpg, original)]
I20160705-10:41:31.535(5.5)? [FilesCollection] [serve(assets\app\uploads\Images/a3tDdoBiqrZv7EMQa.jpg, original)] [200]
I20160705-10:44:25.359(5.5)? [FilesCollection] [File Start Method] IMG_20160605_212301.jpg - 5Hqmzot9kzaMG93ji
I20160705-10:44:25.377(5.5)? [FilesCollection] [Upload] [Start Method] Got #-1/12 chunks, dst: IMG_20160605_212301.jpg
I20160705-10:44:26.230(5.5)? [FilesCollection] [Upload] [DDP] Got #1/12 chunks, dst: IMG_20160605_212301.jpg
I20160705-10:44:26.382(5.5)? [FilesCollection] [Upload] [DDP] Got #2/12 chunks, dst: IMG_20160605_212301.jpg
I20160705-10:44:26.529(5.5)? [FilesCollection] [Upload] [DDP] Got #3/12 chunks, dst: IMG_20160605_212301.jpg
I20160705-10:44:26.638(5.5)? [FilesCollection] [Upload] [DDP] Got #4/12 chunks, dst: IMG_20160605_212301.jpg
I20160705-10:44:26.813(5.5)? [FilesCollection] [Upload] [DDP] Got #5/12 chunks, dst: IMG_20160605_212301.jpg
I20160705-10:44:27.136(5.5)? [FilesCollection] [Upload] [DDP] Got #6/12 chunks, dst: IMG_20160605_212301.jpg
I20160705-10:44:27.156(5.5)? [FilesCollection] [Upload] [DDP] Got #7/12 chunks, dst: IMG_20160605_212301.jpg
I20160705-10:44:27.285(5.5)? [FilesCollection] [Upload] [DDP] Got #8/12 chunks, dst: IMG_20160605_212301.jpg
I20160705-10:44:27.450(5.5)? [FilesCollection] [Upload] [DDP] Got #9/12 chunks, dst: IMG_20160605_212301.jpg
I20160705-10:44:27.599(5.5)? [FilesCollection] [Upload] [DDP] Got #10/12 chunks, dst: IMG_20160605_212301.jpg
I20160705-10:44:27.714(5.5)? [FilesCollection] [Upload] [DDP] Got #11/12 chunks, dst: IMG_20160605_212301.jpg
I20160705-10:44:27.825(5.5)? [FilesCollection] [Upload] [DDP] Got #12/12 chunks, dst: IMG_20160605_212301.jpg
I20160705-10:44:27.852(5.5)? [FilesCollection] [Upload] [DDP] Got #-1/12 chunks, dst: IMG_20160605_212301.jpg
I20160705-10:44:27.853(5.5)? [FilesCollection] [Upload] [finish(ing)Upload] -> assets\app\uploads\Images/5Hqmzot9kzaMG93ji.jpg
I20160705-10:44:27.855(5.5)? [FilesCollection] [Upload] [finish(ed)Upload] -> assets\app\uploads\Images/5Hqmzot9kzaMG93ji.jpg
I20160705-10:44:27.858(5.5)? [FilesCollection] [_preCollectionCursor.observeChanges] [removed]: 5Hqmzot9kzaMG93ji
I20160705-10:44:28.503(5.5)? [FilesCollection] [download(/cdn/storage/Images/5Hqmzot9kzaMG93ji/original/5Hqmzot9kzaMG93ji.jpg, original)]
I20160705-10:44:28.523(5.5)? [FilesCollection] [serve(assets\app\uploads\Images/5Hqmzot9kzaMG93ji.jpg, original)] [200]
I20160705-10:44:28.888(5.5)? [FilesCollection] [download(/cdn/storage/Images/5Hqmzot9kzaMG93ji/original/5Hqmzot9kzaMG93ji.jpg, original)]
I20160705-10:44:28.888(5.5)? [FilesCollection] [serve(assets\app\uploads\Images/5Hqmzot9kzaMG93ji.jpg, original)] [200]
I20160705-10:44:47.354(5.5)? [FilesCollection] [find({}, undefined)]
I20160705-10:44:47.822(5.5)? [FilesCollection] [download(/cdn/storage/Images/5Hqmzot9kzaMG93ji/original/5Hqmzot9kzaMG93ji.jpg, original)]
I20160705-10:44:47.824(5.5)? [FilesCollection] [serve(assets\app\uploads\Images/5Hqmzot9kzaMG93ji.jpg, original)] [200]
I20160705-10:44:47.827(5.5)? [FilesCollection] [download(/cdn/storage/Images/a3tDdoBiqrZv7EMQa/original/a3tDdoBiqrZv7EMQa.jpg, original)]
I20160705-10:44:47.827(5.5)? [FilesCollection] [serve(assets\app\uploads\Images/a3tDdoBiqrZv7EMQa.jpg, original)] [200]
I20160705-10:44:47.827(5.5)? [FilesCollection] [download(/cdn/storage/Images/ca3nAxcREBSXdaxSG/original/ca3nAxcREBSXdaxSG.jpg, original)]
I20160705-10:44:47.827(5.5)? [FilesCollection] [serve(assets\app\uploads\Images/ca3nAxcREBSXdaxSG.jpg, original)] [200]
I20160705-10:44:47.827(5.5)? [FilesCollection] [download(/cdn/storage/Images/nJSndq69wW9RkCdvQ/original/nJSndq69wW9RkCdvQ.jpg, original)]
I20160705-10:44:47.827(5.5)? [FilesCollection] [serve(assets\app\uploads\Images/nJSndq69wW9RkCdvQ.jpg, original)] [200]
I20160705-10:44:47.827(5.5)? [FilesCollection] [download(/cdn/storage/Images/f8pf4mKmrQFEYLNKP/original/f8pf4mKmrQFEYLNKP.jpg, original)]
I20160705-10:44:47.827(5.5)? [FilesCollection] [serve(assets\app\uploads\Images/f8pf4mKmrQFEYLNKP.jpg, original)] [200]
I20160705-11:06:00.164(5.5)? [FilesCollection] [find({}, undefined)]
I20160705-11:54:11.865(5.5)? [FilesCollection] [find({}, undefined)]
I20160705-11:55:17.660(5.5)? [FilesCollection] [find({}, undefined)]
```

**Comment by dr-dimitru** [comment]
This is known bug, and it is fixed (*at least should be*) in `1.6.2`
Please update from `dev` branch. If it will work for you I'll publish a new release

**Comment by dr-dimitru** [comment]
@JohnMKC any news on your end?

**Comment by JohnMKC** [comment]
@dr-dimitru  : Sorry for delay. It's working fine as it should.

**Comment by ferdiemcdaniel** [comment]
Hi,

I am on v1.6.9 for Meteor Files yet i'm still getting this error.
I have the correct publications and subscriptions, if this is not the problem what might be causing this problem?

**Comment by dr-dimitru** [comment]
@ferdiemcdaniel show me your code

**Comment by ferdiemcdaniel** [comment]
`onDrop(files) {
        console.log(this.props.section);
        if (files && files[0]) {
            Images.insert({
                file: files[0],
                meta: {
                    tag: this.props.section
                },
                transport: 'ddp',
                streams: 'dynamic',
                chunkSize: 'dynamic',
                onStart: (error, fileData) => {
                  this.setState({fileState: fileData});
                },
                onUploaded: (error, fileData) => {
                  let file = Images.findOne({_id: fileData._id});
                  this.setState({fileState: false, fileLink: file.link()});
                },
                onError: (error, fileObj) => {
                    alert('Error during upload: ' + error);
                }
            });
        }
    }`

I am using meteor-react. My problem is that hooks like 'uploaded' and 'end' are triggered even if fileData is not yet with in the collection.

**Comment by dr-dimitru** [comment]
- First: `onStart` and  `onUploaded` has its own context, so there id no `this.setState()` method
 - Why would you do `file = Images.findOne({_id: fileData._id});` when `fileData` will be equal to `file`
 - Try to use event-oriented style
 - What yours errors? Stack trace? What debug logs says use `debug: true` passed to MF Constructor?

**Comment by ferdiemcdaniel** [comment]
Here's the logs

`[FilesCollection] [insert()] ostrio_files.js?hash=2b0b489…:2944
[FilesCollection] [insert] [Tracker] [continue] ostrio_files.js?hash=2b0b489…:3045
[FilesCollection] [insert] [.continue()] ostrio_files.js?hash=2b0b489…:2972
[FilesCollection] [insert] using WebWorkers ostrio_files.js?hash=2b0b489…:2720 
loadFile lighter-lighters-ace-fire-hd-macro-photo-wallpaper-desktop-background.jpg: 63.923ms ostrio_files.js?hash=2b0b489…:2681
insert lighter-lighters-ace-fire-hd-macro-photo-wallpaper-desktop-background.jpg: 119.066ms ostrio_files.js?hash=2b0b489…:2464
[FilesCollection] [findOne({"_id":"yfFzu2ziinHfYgJuE"}, undefined)]
debug.js:41 Exception in delivering result of invoking '_FilesCollectionWrite_Images': TypeError: Cannot read property 'link' of undefined
    at FileUpload.onUploaded (http://localhost:3000/app/app.js?hash=b168c9c9f5a83dadc99f54f8a4e24e17601795b1:6431:79)
    at UploadInstance.module.runModuleSetters.FilesCollection._UploadInstance.Meteor.isClient.UploadInstance.end (http://localhost:3000/packages/ostrio_files.js?hash=2b0b4896204d2480109463d3e3c84d524db2deed:2685:56)
    at UploadInstance.emitEvent (http://localhost:3000/packages/ostrio_files.js?hash=2b0b4896204d2480109463d3e3c84d524db2deed:481:42)
    at http://localhost:3000/packages/ostrio_files.js?hash=2b0b4896204d2480109463d3e3c84d524db2deed:2783:18
    at MethodInvoker.Meteor.bindEnvironment [as _callback] (http://localhost:3000/packages/meteor.js?hash=ae8b8affa9680bf9720bd8f7fa112f13a62f71c3:1105:22)
    at MethodInvoker._maybeInvokeCallback (http://localhost:3000/packages/ddp-client.js?hash=27502404fad7fc072e57e8b0b6719f40d92709c7:3557:12)
    at MethodInvoker.receiveResult (http://localhost:3000/packages/ddp-client.js?hash=27502404fad7fc072e57e8b0b6719f40d92709c7:3577:10)
    at Connection._livedata_result (http://localhost:3000/packages/ddp-client.js?hash=27502404fad7fc072e57e8b0b6719f40d92709c7:4742:9)
    at onMessage (http://localhost:3000/packages/ddp-client.js?hash=27502404fad7fc072e57e8b0b6719f40d92709c7:3385:12)
    at http://localhost:3000/packages/ddp-client.js?hash=27502404fad7fc072e57e8b0b6719f40d92709c7:2736:11`

I'm just trying to get the link for the file I uploaded.

**Comment by dr-dimitru** [comment]
Got it:
```js
Images.link(fileData);
```

**Comment by ferdiemcdaniel** [comment]
worked perfectly. Thank you so much.

**Comment by dr-dimitru** [comment]
@ferdiemcdaniel Great, glad you've solved it

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)
