### ISSUE TITLE
Multiple uploads abort with a "session expired" message

### ISSUE THREAD

**Issue by RavDanny** [VeliovGroup/Meteor-Files#452]
### I'm having an issue:
  - Version of `Meteor-Files`: 1.17.3
  - Version of `Meteor`: 1.5
  - Both *Client* and *Server* issue

I have two upload panels as children within a parent form panel.

My app was working fine with multiple file uploads (e.g. 3 files, each < 4 Mb) from a single panel for a long time. However, once I started uploading significantly larger single files (e.g. 19Mb) or multiple large files (e.g. 3 x 7.7Mb) I would get the problems below. Or if I had multiple file uploads and I aborted one or more, occasionally they would all abort. Alternatively, if I did an upload in one panel and then began an upload in the second panel, the first upload would usually be interrupted, although not necessarily immediately. Once the problem happened once, it would seem to occur more frequently.

Not sure if this is related, but a user reported that after resizing the screen on MacOS the progress percentage meter (using progress.get) went back to 0%, and he wasn't sure if the upload continued. (I've been using Chrome on a Windows machine and haven't seen this problem.)

See the server and client console logs below.

Could the problem be related to a problem with my network setup (app inside a Docker container, NGINX proxy running from outside the container)?

Thanks

Server logs:
```
I20170618-12:15:39.556(0)? [FilesCollection] [find(undefined, undefined)]
I20170618-12:15:55.332(0)? [FilesCollection] [File Start Method] AmpleroFluxnet1.0Cable1.4b.nc - KvytMfnJ9Gbo9BRi9
I20170618-12:15:55.334(0)? [FilesCollection] [Upload] [DDP Start Method] Got #-1/24 chunks, dst: AmpleroFluxnet1.0Cable1.4b.nc
I20170618-12:15:55.338(0)? [FilesCollection] [File Start Method] AmpleroFluxnet1.2Cable1.4b.nc - azDEHWJuwCBvGTeMF
I20170618-12:15:55.339(0)? [FilesCollection] [Upload] [DDP Start Method] Got #-1/24 chunks, dst: AmpleroFluxnet1.2Cable1.4b.nc
I20170618-12:15:55.346(0)? [FilesCollection] [File Start Method] AmpleroFluxnet1.3Cable1.4b.nc - PuZpC5zgNAxpAGz7m
I20170618-12:15:55.346(0)? [FilesCollection] [Upload] [DDP Start Method] Got #-1/24 chunks, dst: AmpleroFluxnet1.3Cable1.4b.nc
I20170618-12:15:57.787(0)? [FilesCollection] [Upload] [DDP] Got #1/24 chunks, dst: AmpleroFluxnet1.0Cable1.4b.nc
I20170618-12:15:59.767(0)? [FilesCollection] [Upload] [DDP] Got #1/24 chunks, dst: AmpleroFluxnet1.2Cable1.4b.nc
I20170618-12:16:01.793(0)? [FilesCollection] [Upload] [DDP] Got #2/24 chunks, dst: AmpleroFluxnet1.0Cable1.4b.nc
I20170618-12:16:03.642(0)? [FilesCollection] [Upload] [DDP] Got #2/24 chunks, dst: AmpleroFluxnet1.2Cable1.4b.nc
I20170618-12:16:05.829(0)? [FilesCollection] [Upload] [DDP] Got #3/24 chunks, dst: AmpleroFluxnet1.2Cable1.4b.nc
I20170618-12:16:07.940(0)? [FilesCollection] [Upload] [DDP] Got #3/24 chunks, dst: AmpleroFluxnet1.0Cable1.4b.nc
I20170618-12:16:09.839(0)? [FilesCollection] [Upload] [DDP] Got #4/24 chunks, dst: AmpleroFluxnet1.0Cable1.4b.nc
I20170618-12:16:11.764(0)? [FilesCollection] [Upload] [DDP] Got #5/24 chunks, dst: AmpleroFluxnet1.0Cable1.4b.nc
I20170618-12:16:13.714(0)? [FilesCollection] [Upload] [DDP] Got #6/24 chunks, dst: AmpleroFluxnet1.0Cable1.4b.nc
I20170618-12:16:15.879(0)? [FilesCollection] [Upload] [DDP] Got #1/24 chunks, dst: AmpleroFluxnet1.3Cable1.4b.nc
I20170618-12:16:17.895(0)? [FilesCollection] [Upload] [DDP] Got #7/24 chunks, dst: AmpleroFluxnet1.0Cable1.4b.nc
I20170618-12:16:20.028(0)? [FilesCollection] [Upload] [DDP] Got #8/24 chunks, dst: AmpleroFluxnet1.0Cable1.4b.nc
I20170618-12:16:21.938(0)? [FilesCollection] [Upload] [DDP] Got #9/24 chunks, dst: AmpleroFluxnet1.0Cable1.4b.nc
I20170618-12:16:24.124(0)? [FilesCollection] [Upload] [DDP] Got #2/24 chunks, dst: AmpleroFluxnet1.3Cable1.4b.nc
I20170618-12:16:26.374(0)? [FilesCollection] [Upload] [DDP] Got #3/24 chunks, dst: AmpleroFluxnet1.3Cable1.4b.nc
I20170618-12:16:28.246(0)? [FilesCollection] [Upload] [DDP] Got #10/24 chunks, dst: AmpleroFluxnet1.0Cable1.4b.nc
I20170618-12:16:30.532(0)? [FilesCollection] [Upload] [DDP] Got #4/24 chunks, dst: AmpleroFluxnet1.3Cable1.4b.nc
I20170618-12:16:32.736(0)? [FilesCollection] [Upload] [DDP] Got #5/24 chunks, dst: AmpleroFluxnet1.3Cable1.4b.nc
I20170618-12:16:34.597(0)? [FilesCollection] [Upload] [DDP] Got #11/24 chunks, dst: AmpleroFluxnet1.0Cable1.4b.nc
I20170618-12:16:36.873(0)? [FilesCollection] [Upload] [DDP] Got #6/24 chunks, dst: AmpleroFluxnet1.3Cable1.4b.nc
I20170618-12:16:39.181(0)? [FilesCollection] [Upload] [DDP] Got #7/24 chunks, dst: AmpleroFluxnet1.3Cable1.4b.nc
I20170618-12:16:41.521(0)? [FilesCollection] [Upload] [DDP] Got #8/24 chunks, dst: AmpleroFluxnet1.3Cable1.4b.nc
I20170618-12:16:43.248(0)? [FilesCollection] [_preCollectionCursor.observe] [removed]: KvytMfnJ9Gbo9BRi9
I20170618-12:16:43.249(0)? [FilesCollection] [_preCollectionCursor.observe] [removeUnfinishedUpload]: KvytMfnJ9Gbo9BRi9
I20170618-12:16:43.249(0)? [FilesCollection] [_preCollectionCursor.observe] [removed]: azDEHWJuwCBvGTeMF
I20170618-12:16:43.250(0)? [FilesCollection] [_preCollectionCursor.observe] [removeUnfinishedUpload]: azDEHWJuwCBvGTeMF
I20170618-12:16:43.251(0)? [FilesCollection] [_preCollectionCursor.observe] [removed]: PuZpC5zgNAxpAGz7m
I20170618-12:16:43.251(0)? [FilesCollection] [_preCollectionCursor.observe] [removeUnfinishedUpload]: PuZpC5zgNAxpAGz7m
I20170618-12:18:24.186(0)? [FilesCollection] [Abort Method]: PuZpC5zgNAxpAGz7m - undefined
I20170618-12:18:24.192(0)? [FilesCollection] [Abort Method]: KvytMfnJ9Gbo9BRi9 - undefined
I20170618-12:18:24.197(0)? [FilesCollection] [Abort Method]: azDEHWJuwCBvGTeMF - undefined
```

Client log:
```
[FilesCollection] [insert] [.pause()]
ostrio_files.js?hash=7f7b125…:2857 insert AmpleroFluxnet1.0Cable1.4b.nc: 52934.06689453125ms
ostrio_files.js?hash=7f7b125…:2398 insert AmpleroFluxnet1.2Cable1.4b.nc: 71672.9677734375ms
ostrio_files.js?hash=7f7b125…:2405 [FilesCollection] [insert] [end] Error: errorClass {error: 408, reason: "Can't continue upload, session expired. Start upload again.", details: undefined, message: "Can't continue upload, session expired. Start upload again. [408]", errorType: "Meteor.Error"…}
module.runModuleSetters.FilesCollection._UploadInstance.Meteor.isClient.UploadInstance.end @ ostrio_files.js?hash=7f7b125…:2405
emitEvent @ event-emitter.jsx:373
(anonymous) @ ostrio_files.js?hash=7f7b125…:2457
(anonymous) @ meteor.js?hash=27829e9…:1105
_maybeInvokeCallback @ livedata_connection.js:442
receiveResult @ livedata_connection.js:462
_livedata_result @ livedata_connection.js:1624
onMessage @ livedata_connection.js:277
(anonymous) @ stream_client_sockjs.js:174
_.each._.forEach @ underscore.js?hash=cde485f…:149
self.socket.onmessage @ stream_client_sockjs.js:173
REventTarget.dispatchEvent @ sockjs-0.3.4.js:87
SockJS._dispatchMessage @ sockjs-0.3.4.js:1072
SockJS._didMessage @ sockjs-0.3.4.js:1130
that.ws.onmessage @ sockjs-0.3.4.js:1277
ostrio_files.js?hash=7f7b125…:2848 [FilesCollection] [insert] [.abort()]
global.js:29 File upload aborted Object {} UserId:  zLpnZbjFvyhr2p4ex
ostrio_files.js?hash=7f7b125…:2814 [FilesCollection] [insert] [.pause()]
ostrio_files.js?hash=7f7b125…:2857 insert AmpleroFluxnet1.2Cable1.4b.nc: 71682.8837890625ms
```

**Comment by dr-dimitru** [comment]
Hello @RavDanny ,

> Version of Meteor-Files: 1.17.3

Have you tried to upgrade to the latest release? Lots of things was fixed, especially for Meteor@1.5.

>  larger single files (e.g. 19Mb)

We're running fine with multi-gygabyte uploads.

> session expired

This may occur only in case if upload takes significant amount of time. There is `continueUploadTTL` option which is responsible for this, and defaults to 3 hours. Is uploads takes more than 3 hours, or `continueUploadTTL` set to very small value?

From current point of view it looks like familiar bug from the past. try to update to the latest release in first place. Let's see if it will help.

**Comment by RavDanny** [comment]
Hi @dr-dimitru,

Thanks for the quick reply.

I tried to upgrade but it was extracting endlessly. Any tips for that?

**Comment by dr-dimitru** [comment]
You may try `meteor reset` (__note__: *it will drop local Mongo*)
Also make sure `meteor-node-stubs` in its latest release `0.2.11`
```shell
meteor npm outdated
meteor npm update --save
```

**Comment by RavDanny** [comment]
Hi,

It's now updated, but the problem is still happening, as per below.
As you can see, the problem happens after a very short time. I didn't make
any changes to `continueUploadTTL`.

```
Client:
[FilesCollection] [insert] [end] Error: errorClass {error: 408, reason:
"Can't continue upload, session expired. Start upload again.", details:
undefined, message: "Can't continue upload, session expired. Start upload
again. [408]", errorType: "Meteor.Error"…}

Server:
I20170619-08:11:39.546(0)? Successful login  UserId:  zLpnZbjFvyhr2p4ex
I20170619-08:11:39.585(0)? [FilesCollection] [find(undefined, undefined)]
I20170619-08:12:17.887(0)? [FilesCollection] [File Start Method]
BondvFluxnet1.0Cable1.4b.nc - cPDstoJeRF2XxnEx8
I20170619-08:12:17.891(0)? [FilesCollection] [Upload] [DDP Start Method]
Got #-1/60 chunks, dst: BondvFluxnet1.0Cable1.4b.nc
I20170619-08:12:20.013(0)? [FilesCollection] [Upload] [DDP] Got #1/60
chunks, dst: BondvFluxnet1.0Cable1.4b.nc
I20170619-08:12:21.858(0)? [FilesCollection] [Upload] [DDP] Got #2/60
chunks, dst: BondvFluxnet1.0Cable1.4b.nc
I20170619-08:12:23.708(0)? [FilesCollection] [Upload] [DDP] Got #3/60
chunks, dst: BondvFluxnet1.0Cable1.4b.nc
I20170619-08:12:25.570(0)? [FilesCollection] [Upload] [DDP] Got #4/60
chunks, dst: BondvFluxnet1.0Cable1.4b.nc
I20170619-08:12:27.435(0)? [FilesCollection] [Upload] [DDP] Got #5/60
chunks, dst: BondvFluxnet1.0Cable1.4b.nc
I20170619-08:12:29.289(0)? [FilesCollection] [Upload] [DDP] Got #6/60
chunks, dst: BondvFluxnet1.0Cable1.4b.nc
I20170619-08:12:31.150(0)? [FilesCollection] [Upload] [DDP] Got #7/60
chunks, dst: BondvFluxnet1.0Cable1.4b.nc
I20170619-08:12:33.109(0)? [FilesCollection] [Upload] [DDP] Got #8/60
chunks, dst: BondvFluxnet1.0Cable1.4b.nc
I20170619-08:12:34.975(0)? [FilesCollection] [Upload] [DDP] Got #9/60
chunks, dst: BondvFluxnet1.0Cable1.4b.nc
I20170619-08:12:36.827(0)? [FilesCollection] [Upload] [DDP] Got #10/60
chunks, dst: BondvFluxnet1.0Cable1.4b.nc
I20170619-08:12:38.632(0)? [FilesCollection] [Upload] [DDP] Got #11/60
chunks, dst: BondvFluxnet1.0Cable1.4b.nc
I20170619-08:12:40.431(0)? [FilesCollection] [Upload] [DDP] Got #12/60
chunks, dst: BondvFluxnet1.0Cable1.4b.nc
I20170619-08:12:42.262(0)? [FilesCollection] [Upload] [DDP] Got #13/60
chunks, dst: BondvFluxnet1.0Cable1.4b.nc
I20170619-08:12:43.469(0)? [FilesCollection] [_preCollectionCursor.observe]
[removed]: cPDstoJeRF2XxnEx8
I20170619-08:12:43.472(0)? [FilesCollection] [_preCollectionCursor.observe]
[removeUnfinishedUpload]: cPDstoJeRF2XxnEx8
I20170619-08:13:28.430(0)? [FilesCollection] [Abort Method]:
cPDstoJeRF2XxnEx8 - undefined
```

**Comment by dr-dimitru** [comment]
Well... 
 1. Does Nginx has something in its logs?
 2. Where your hosting is?
 3. What kind of deployment are you using?
 4. Is sticky sessions on?
 5. Have you tried HTTP transport instead of DDP?

**Comment by RavDanny** [comment]
1. Nginx is showing errors when loading the page, but not while the uploads are happening.

**/var/log/nginx/error.log:**
```
2017/06/20 07:26:50 [error] 813#813: *82583 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: <client ip address>, server: <website>.org, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "<website>.org"
2017/06/20 09:26:43 [error] 813#813: *82871 connect() failed (111: Connection refused) while connecting to upstream, client: <client ip address>, server: <website>.org, request: "GET /sockjs/info?cb=tjfctd2pct HTTP/1.1", upstream: "http://[::1]:3000/sockjs/info?cb=tjfctd2pct", host: "<website>.org", referrer: "https://<website>.org/dataSet/create"
```
2. Hosting on NectarCloud Openstack instances
3. Not quite what that means - the Meteor app runs inside a Docker container, with Nginx outside of the container.
4. I don't know how to turn on Sticky Sessions.
5. This is what happens with HTTP on the server console:

```
I20170620-09:49:31.003(0)? [FilesCollection] [File Start HTTP] BondvFluxnet1.0Cable1.4b.nc - e3RDpYFvtZdKiQkEp
I20170620-09:49:31.008(0)? [FilesCollection] [Upload] [HTTP Start Method] Got #-1/120 chunks, dst: BondvFluxnet1.0Cable1.4b.nc
I20170620-09:49:34.951(0)? [FilesCollection] [Upload] [HTTP] Got #1/120 chunks, dst: BondvFluxnet1.0Cable1.4b.nc
I20170620-09:49:35.224(0)? [FilesCollection] [Upload] [HTTP] Got #2/120 chunks, dst: BondvFluxnet1.0Cable1.4b.nc
I20170620-09:49:37.957(0)? [FilesCollection] [Upload] [HTTP] Got #10/120 chunks, dst: BondvFluxnet1.0Cable1.4b.nc
I20170620-09:49:40.597(0)? [FilesCollection] [Upload] [HTTP] Got #12/120 chunks, dst: BondvFluxnet1.0Cable1.4b.nc
I20170620-09:49:45.571(0)? [FilesCollection] [Upload] [HTTP] Got #3/120 chunks, dst: BondvFluxnet1.0Cable1.4b.nc
I20170620-09:49:49.067(0)? [FilesCollection] [Upload] [HTTP] Got #4/120 chunks, dst: BondvFluxnet1.0Cable1.4b.nc
I20170620-09:49:52.364(0)? [FilesCollection] [Upload] [HTTP] Got #9/120 chunks, dst: BondvFluxnet1.0Cable1.4b.nc
I20170620-09:49:52.726(0)? [FilesCollection] [_preCollectionCursor.observe] [removed]: e3RDpYFvtZdKiQkEp
I20170620-09:49:52.727(0)? [FilesCollection] [_preCollectionCursor.observe] [removeUnfinishedUpload]: e3RDpYFvtZdKiQkEp
W20170620-09:49:52.944(0)? (STDERR) [FilesCollection] [Upload] [HTTP] Exception: { [Error: Can't continue upload, session expired. Start upload again. [408]]
W20170620-09:49:52.947(0)? (STDERR)   error: 408,
W20170620-09:49:52.948(0)? (STDERR)   reason: 'Can\'t continue upload, session expired. Start upload again.',
W20170620-09:49:52.949(0)? (STDERR)   details: undefined,
W20170620-09:49:52.950(0)? (STDERR)   message: 'Can\'t continue upload, session expired. Start upload again. [408]',
W20170620-09:49:52.951(0)? (STDERR)   errorType: 'Meteor.Error' }
I20170620-09:49:54.553(0)? [FilesCollection] [Abort Method]: e3RDpYFvtZdKiQkEp - undefined
W20170620-09:49:54.984(0)? (STDERR) [FilesCollection] [Upload] [HTTP] Exception: { [Error: Can't continue upload, session expired. Start upload again. [408]]
W20170620-09:49:54.987(0)? (STDERR)   error: 408,
W20170620-09:49:54.988(0)? (STDERR)   reason: 'Can\'t continue upload, session expired. Start upload again.',
W20170620-09:49:54.989(0)? (STDERR)   details: undefined,
W20170620-09:49:54.991(0)? (STDERR)   message: 'Can\'t continue upload, session expired. Start upload again. [408]',
W20170620-09:49:54.992(0)? (STDERR)   errorType: 'Meteor.Error' }
W20170620-09:49:57.324(0)? (STDERR) [FilesCollection] [Upload] [HTTP] Exception: { [Error: Can't continue upload, session expired. Start upload again. [408]]
W20170620-09:49:57.325(0)? (STDERR)   error: 408,
W20170620-09:49:57.329(0)? (STDERR)   reason: 'Can\'t continue upload, session expired. Start upload again.',
W20170620-09:49:57.332(0)? (STDERR)   details: undefined,
W20170620-09:49:57.333(0)? (STDERR)   message: 'Can\'t continue upload, session expired. Start upload again. [408]',
W20170620-09:49:57.335(0)? (STDERR)   errorType: 'Meteor.Error' }
W20170620-09:50:00.988(0)? (STDERR) [FilesCollection] [Upload] [HTTP] Exception: { [Error: Can't continue upload, session expired. Start upload again. [408]]
W20170620-09:50:00.990(0)? (STDERR)   error: 408,
W20170620-09:50:00.992(0)? (STDERR)   reason: 'Can\'t continue upload, session expired. Start upload again.',
W20170620-09:50:00.993(0)? (STDERR)   details: undefined,
W20170620-09:50:00.994(0)? (STDERR)   message: 'Can\'t continue upload, session expired. Start upload again. [408]',
W20170620-09:50:00.994(0)? (STDERR)   errorType: 'Meteor.Error' }
W20170620-09:50:01.465(0)? (STDERR) [FilesCollection] [Upload] [HTTP] Exception: { [Error: Can't continue upload, session expired. Start upload again. [408]]
W20170620-09:50:01.466(0)? (STDERR)   error: 408,
W20170620-09:50:01.467(0)? (STDERR)   reason: 'Can\'t continue upload, session expired. Start upload again.',
W20170620-09:50:01.468(0)? (STDERR)   details: undefined,
W20170620-09:50:01.471(0)? (STDERR)   message: 'Can\'t continue upload, session expired. Start upload again. [408]',
W20170620-09:50:01.471(0)? (STDERR)   errorType: 'Meteor.Error' }
W20170620-09:50:01.865(0)? (STDERR) [FilesCollection] [Upload] [HTTP] Exception: { [Error: Can't continue upload, session expired. Start upload again. [408]]
W20170620-09:50:01.866(0)? (STDERR)   error: 408,
W20170620-09:50:01.867(0)? (STDERR)   reason: 'Can\'t continue upload, session expired. Start upload again.',
W20170620-09:50:01.868(0)? (STDERR)   details: undefined,
W20170620-09:50:01.869(0)? (STDERR)   message: 'Can\'t continue upload, session expired. Start upload again. [408]',
W20170620-09:50:01.870(0)? (STDERR)   errorType: 'Meteor.Error' }
W20170620-09:50:02.004(0)? (STDERR) [FilesCollection] [Upload] [HTTP] Exception: { [Error: Can't continue upload, session expired. Start upload again. [408]]
W20170620-09:50:02.005(0)? (STDERR)   error: 408,
W20170620-09:50:02.006(0)? (STDERR)   reason: 'Can\'t continue upload, session expired. Start upload again.',
W20170620-09:50:02.007(0)? (STDERR)   details: undefined,
W20170620-09:50:02.008(0)? (STDERR)   message: 'Can\'t continue upload, session expired. Start upload again. [408]',
W20170620-09:50:02.009(0)? (STDERR)   errorType: 'Meteor.Error' }
W20170620-09:50:06.385(0)? (STDERR) [FilesCollection] [Upload] [HTTP] Exception: { [Error: Can't continue upload, session expired. Start upload again. [408]]
W20170620-09:50:06.386(0)? (STDERR)   error: 408,
W20170620-09:50:06.387(0)? (STDERR)   reason: 'Can\'t continue upload, session expired. Start upload again.',
W20170620-09:50:06.388(0)? (STDERR)   details: undefined,
W20170620-09:50:06.389(0)? (STDERR)   message: 'Can\'t continue upload, session expired. Start upload again. [408]',
W20170620-09:50:06.390(0)? (STDERR)   errorType: 'Meteor.Error' }
W20170620-09:50:06.832(0)? (STDERR) [FilesCollection] [Upload] [HTTP] Exception: { [Error: Can't continue upload, session expired. Start upload again. [408]]
W20170620-09:50:06.834(0)? (STDERR)   error: 408,
W20170620-09:50:06.835(0)? (STDERR)   reason: 'Can\'t continue upload, session expired. Start upload again.',
W20170620-09:50:06.836(0)? (STDERR)   details: undefined,
W20170620-09:50:06.837(0)? (STDERR)   message: 'Can\'t continue upload, session expired. Start upload again. [408]',
W20170620-09:50:06.838(0)? (STDERR)   errorType: 'Meteor.Error' }
W20170620-09:50:07.113(0)? (STDERR) [FilesCollection] [Upload] [HTTP] Exception: { [Error: Can't continue upload, session expired. Start upload again. [408]]
W20170620-09:50:07.115(0)? (STDERR)   error: 408,
W20170620-09:50:07.116(0)? (STDERR)   reason: 'Can\'t continue upload, session expired. Start upload again.',
W20170620-09:50:07.117(0)? (STDERR)   details: undefined,
W20170620-09:50:07.118(0)? (STDERR)   message: 'Can\'t continue upload, session expired. Start upload again. [408]',
W20170620-09:50:07.119(0)? (STDERR)   errorType: 'Meteor.Error' }
W20170620-09:50:09.302(0)? (STDERR) [FilesCollection] [Upload] [HTTP] Exception: { [Error: Can't continue upload, session expired. Start upload again. [408]]
W20170620-09:50:09.303(0)? (STDERR)   error: 408,
W20170620-09:50:09.304(0)? (STDERR)   reason: 'Can\'t continue upload, session expired. Start upload again.',
W20170620-09:50:09.306(0)? (STDERR)   details: undefined,
W20170620-09:50:09.307(0)? (STDERR)   message: 'Can\'t continue upload, session expired. Start upload again. [408]',
W20170620-09:50:09.309(0)? (STDERR)   errorType: 'Meteor.Error' }
W20170620-09:50:09.420(0)? (STDERR) [FilesCollection] [Upload] [HTTP] Exception: { [Error: Can't continue upload, session expired. Start upload again. [408]]
W20170620-09:50:09.422(0)? (STDERR)   error: 408,
W20170620-09:50:09.423(0)? (STDERR)   reason: 'Can\'t continue upload, session expired. Start upload again.',
W20170620-09:50:09.424(0)? (STDERR)   details: undefined,
W20170620-09:50:09.425(0)? (STDERR)   message: 'Can\'t continue upload, session expired. Start upload again. [408]',
W20170620-09:50:09.426(0)? (STDERR)   errorType: 'Meteor.Error' }
```

**Comment by dr-dimitru** [comment]
Please read this Docker related article - https://github.com/VeliovGroup/Meteor-Files/wiki/MeteorUp-(MUP)-Usage

**Comment by RavDanny** [comment]
I'm not experiencing the problem any more. The nginx configuration that was provided to me apparently had some glitches in it. I set up a new configuration from scratch and the problem went away.
Thanks for your help.

**Comment by RavDanny** [comment]
I spoke too soon.
After fixing the Nginx configuration I have not had any problems with uploading large files. A problem still arises when I try to upload files in a second upload panel while an upload is still taking place in the first upload panel. This usually leads to the session expired error. Is this an expected problem (in which case I can work around it if necessary) or not?
Thanks

**Comment by dr-dimitru** [comment]
> I don't have an upstream block. Do I need one?

It's better to manage `proxy_pass` via upstream block with [`keepalive`](http://nginx.org/en/docs/http/ngx_http_upstream_module.html#keepalive) option.

Also I don't see how you manage websockets here, do you have a `$http_upgrade` rule set?

As far as I'm see if you application is working with out issues (except file uploads) it's not Nginx issue.
Perhaps Client or Server runs out of the memory, or memory dedicated for the process. I'm suggesting to tune `chunkSize`, although it's suggested to be `dynamic` in your case it might be better so set to some constraint for large files. Let me know if it will change or solve this issue.

**Comment by dr-dimitru** [comment]
Here is some links:
 - [Sticky session via `ip_hash`](http://nginx.org/en/docs/http/ngx_http_upstream_module.html#ip_hash)
 - [Sticky Sessions in Nginx Plus](https://www.nginx.com/products/session-persistence/)

**Comment by dr-dimitru** [comment]
I've ran load stress tests on my heroku deployment, upload is paused once server reached 512MB memory limit, and continued after connection is established again.

**Comment by RavDanny** [comment]
> It's better to manage proxy_pass via upstream block with keepalive option.

That alone made a big difference. It seems to be working now. When I abort an upload it still generates the session-expired error a number of times. Is that expected behaviour?

**Comment by dr-dimitru** [comment]
> Is that expected behaviour?

Yes, only for abort action, as chunks is sent asynchronously some of them may arrive on the Server after "abort" is called.

> That alone made a big difference. It seems to be working now.

Could you share your experience, what was at the beginning, what you have changed to make it work?
I'll probably use it to make a wiki page for Nginx setup

**Comment by RavDanny** [comment]
I was about to do so today, but new errors have come up preventing my website from loading, so obviously I have more to do to fix up the Nginx...

**Comment by dr-dimitru** [comment]
Thank you for update @RavDanny 
Let me know once it will work for you

**Comment by RavDanny** [comment]
Sure. I've solved most of the problems.
The only problem that remains is that in the Safari browser for windows I get an error preventing uploads:
```
Error during WebSocket handshake: location mismatch: wss://xxxxxxxxxxxxxx.xxx/sockjs/716/6yoo7mit/websocket != ws://xxxxxxxxxxxxxx.xxx/sockjs/716/6yoo7mit/websocket

app.js:9822
Uploading file 
Object UserId:  zLpnZbjFvyhr2p4ex

ostrio_files.js:1391TypeError: 'undefined' is not a function (evaluating 'this.config.file.slice(this.config.chunkSize * (chunkId - 1), this.config.chunkSize * chunkId)')
```

I assume this is an Nginx problem, not a Meteor-files problem.

**Comment by dr-dimitru** [comment]
@RavDanny have you set `https` protocol explicitly in `ROOT_URL`?

**Comment by RavDanny** [comment]
I didn't set ROOT_URL at all. I just now tried setting it, and the same problem occurred.

I just realised that the initial error ('handshake') happened with startup, while the 'ostrio-files' error only happened with upload. Are they necessarily related?

**Comment by dr-dimitru** [comment]
Okay, now it's more clear.

My guess this line:
```
Error during WebSocket handshake: location mismatch: wss://xxxxxxxxxxxxxx.xxx/sockjs/716/6yoo7mit/websocket != ws://xxxxxxxxxxxxxx.xxx/sockjs/716/6yoo7mit/websocket
```
Means WebSocket connection is somehow failed, - switch to HTTP.

Than you're trying to upload file via broken connection, which leads the second error.
Anyways this looks weird, as socket.io should silently fallback to HTTP in case of the error.

**Comment by dr-dimitru** [comment]
Other guess:
You're running Nginx or Node.js process on http and https or vise versa and protocols are mismatch on some stage. 

What your current infrastructure?

[https request] -> [nginx] -> [node.js] ?

 1. How do you spawn node.js process
 2. Is CloudFlare or something similar is involved?

**Comment by RavDanny** [comment]
I don't run node.js. I have 'meteor run' inside a Docker container, with Nginx outside of the container with a reverse proxy.

**Comment by dr-dimitru** [comment]
> I don't run node.js. I have 'meteor run' inside a Docker container, with Nginx outside of the container with a reverse proxy.

Can't tell mush on such setup, haven't tried it.

Could you post your nginx config?

**Comment by RavDanny** [comment]
**nginx.conf**
```
user www-data;
worker_processes 1;
pid /run/nginx.pid;

events {
        worker_connections 768;
        # multi_accept on;
}

http {

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        # server_tokens off;

        server_names_hash_bucket_size 64;
        # server_name_in_redirect off;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        ##
        # SSL Settings
        ##

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
        ssl_prefer_server_ciphers on;

        ##
        # Logging Settings
        ##

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        ##
        # Gzip Settings
        ##

        gzip on;
        gzip_disable "MSIE [1-6]\.";
# Adding in:
        gzip_proxied any;
        gzip_http_version 1.0;
        gzip_min_length 500;
        gzip_types    text/plain text/xml text/css
                      text/comma-separated-values
                      text/javascript
                      application/x-javascript
                      application/atom+xml;


        ##
        # Virtual Host Configs
        ##

        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
}
```

**sites-available/app**
```
upstream http_backend {
        server 127.0.0.1:8080;
        ip_hash;
        keepalive 16;
}

server {
        #listen 80 default_server;
        #listen [::]:80 default_server;

        # SSL configuration
        #

        listen 443 ssl;

        index index.html index.htm index.nginx-debian.html;

        server_name xxxxxxxxxx.xxxxx;
        ssl_certificate_key /etc/ssl/latest/xxxxxxxxxx;
        ssl_certificate /etc/ssl/latest/xxxxxxxxxxx;

        add_header Strict-Transport-Security "max-age=31536000;";

    # If your application is not compatible with IE <= 10, this will redirect visitors to a page advising a browser update
    # This works because IE 11 does not present itself as MSIE anymore
    if ($http_user_agent ~ "MSIE" ) {
        return 303 https://browser-update.org/update.html;
    }

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                #try_files $uri $uri/ =404;

                proxy_pass http://172.17.0.2:3000;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

#               add_header Cache-Control no-cache;

                client_max_body_size 100M;


        if ($uri != '/') {
            expires 30d;
        }
    }
}
```

**Comment by dr-dimitru** [comment]
So your nginx listens for https on 443, then you proxy pass to `proxy_pass http://172.17.0.2:3000;` *which is http*

I've added to your config:
```nginx
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

location /sockjs/ { ... }

proxy_set_header X-Forwarded-Proto https;
proxy_redirect off;
```

Full updated config:
```nginx
user www-data;
worker_processes 1;
pid /run/nginx.pid;

events {
    worker_connections 768;
    # multi_accept on;
}

http {
    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;
    # server_tokens off;

    server_names_hash_bucket_size 64;
    # server_name_in_redirect off;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    ##
    # SSL Settings
    ##
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
    ssl_prefer_server_ciphers on;

    ##
    # Logging Settings
    ##
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    ##
    # Gzip Settings
    ##
    gzip on;
    gzip_disable "MSIE [1-6]\.";
# Adding in:
    gzip_proxied any;
    gzip_http_version 1.0;
    gzip_min_length 500;
    gzip_types    text/plain text/xml text/css
                  text/comma-separated-values
                  text/javascript
                  application/x-javascript
                  application/atom+xml;


    ##
    # Virtual Host Configs
    ##

    include /etc/nginx/conf.d/*.conf;
    include /etc/nginx/sites-enabled/*;
}

upstream http_backend {
    server 127.0.0.1:8080;
    ip_hash;
    keepalive 16;
}

server {
    #listen 80 default_server;
    #listen [::]:80 default_server;

    # SSL configuration
    #

    listen 443 ssl;

    index index.html index.htm index.nginx-debian.html;

    server_name xxxxxxxxxx.xxxxx;
    ssl_certificate_key /etc/ssl/latest/xxxxxxxxxx;
    ssl_certificate /etc/ssl/latest/xxxxxxxxxxx;

    add_header Strict-Transport-Security "max-age=31536000;";

    # If your application is not compatible with IE <= 10, this will redirect visitors to a page advising a browser update
    # This works because IE 11 does not present itself as MSIE anymore
    if ($http_user_agent ~ "MSIE" ) {
        return 303 https://browser-update.org/update.html;
    }

    location / {
        # First attempt to serve request as file, then
        # as directory, then fall back to displaying a 404.
        #try_files $uri $uri/ =404;

        proxy_pass http://172.17.0.2:3000;
        proxy_http_version 1.1;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto https;
        proxy_redirect     off;

        # add_header Cache-Control no-cache;

        client_max_body_size 100M;


        if ($uri != '/') {
            expires 30d;
        }

        break;
    }

    location /sockjs/ {
        sendfile            off;
        proxy_http_version  1.1;
        proxy_no_cache      1;
        proxy_cache_bypass  1;
        proxy_set_header    Host $host;
        proxy_set_header    X-Real-IP $remote_addr;
        proxy_set_header    Upgrade $http_upgrade;
        proxy_set_header    Connection $connection_upgrade;
        proxy_set_header    X-Forwarded-Proto https;
        proxy_pass http://172.17.0.2:3000;
        break;
    }

    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
}
```

**Comment by dr-dimitru** [comment]
Note: `upstream` should be in `http` block and `proxy_pass` should pass request by `upstream` name

**Comment by RavDanny** [comment]
Are you saying that I should have, for example:
`proxy_pass http_backend;`
instead of: `proxy_pass http://172.17.0.2:3000;`
and:
```
upstream http_backend {
    server 172.17.0.2:3000;
    ip_hash;
    keepalive 16;
}
```
instead of:
```
upstream http_backend {
    server 127.0.0.1:8080;
    ip_hash;
    keepalive 16;
}
```
?

**Comment by dr-dimitru** [comment]
Upstream inside `http` block:
```nginx
    upstream http_backend {
       server 172.17.0.2:3000;
       ip_hash;
       keepalive 16;
    }
```
proxy_pass:
```nginx
proxy_pass http://http_backend;
```

> Where would I put http://172.17.0.2:3000;? Inside the upstream?
> BTW I used your config (without changing the proxy_pass)

It's already changed in suggested config.

Try to use upstream, as it isn't used at all unless you proxy_pass requests by upstream name. Let's see if it will change current error.

**Comment by RavDanny** [comment]
Thanks @dr-dimitru, but it hasn't changed the error.

**Comment by dr-dimitru** [comment]
Hello @RavDanny ,

Could you try fresh [v1.8.1](https://github.com/VeliovGroup/Meteor-Files/releases/tag/1.8.1) release?
No big hope, but there is some enhancements which may fix this issue.

Other thought is to make sure Nectar Cloud have enough resources:
 - How much RAM do you have?
 - What is the storage capacity?
 - Is the storage and file system persistent? (*As example Heroku has no persistent storage*)

**Comment by RavDanny** [comment]
Hi @dr-dimitru,

Thanks for letting me know, although v1.8.1 didn't solve it.
The particular vm has 10G of persistent storage, of which I am only using half.
As for RAM:
```
              total        used        free      shared  buff/cache   available
Mem:            31G        1.1G         24G        352M        5.6G         29G
Swap:            0B          0B          0B
```

**Comment by dr-dimitru** [comment]
Hello @RavDanny ,

Sad to hear.
 1. Is the error changed?
 2. What Nginx version you're on?
 3. Are there any new errors in nginx's logs?
 4. Have you tried same setup without SSL, on 80 port?

**Comment by RavDanny** [comment]
1. No
2. nginx/1.10.0 (Ubuntu)
3. The `connect() failed (111: Connection refused)` error appears. It doesn't happen upon upload or necessarily when opening the page. I'm not sure when it does or doesn't occur.
4. I tried to, but the browser keeps redirecting to `https`. Can't work out what in my config is doing that.

**Comment by dr-dimitru** [comment]
> I tried to, but the browser keeps redirecting to https. Can't work out what in my config is doing that.

It;s not nginx, it's a browser behavior, due to this header:
```nginx
add_header Strict-Transport-Security "max-age=31536000;";
```

Try incognito (private) mode or a browser where you have never visited this website.

**Comment by dr-dimitru** [comment]
> `connect() failed (111: Connection refused)`

Means upstream (the node app) isn't responding to nginx, perhaps nginx started before app

**Comment by RavDanny** [comment]
It's not connecting on `http`
I changed
```
        listen 443 ssl;
```
to 
```
        listen 80 default_server;
        listen [::]:80 default_server;
```
and commented out the ssl certificate lines.
I assume there are other changes I have to make, but I'm not sure what.

**Comment by dr-dimitru** [comment]
Hello @RavDanny ,

Is there any news on this issue?
Have you tried to use Nginx + Phusion Passenger?

**Comment by RavDanny** [comment]
Hi @dr-dimitru ,

No news yet. I was going to see what happened after I custom-deployed it. I haven't had time to do that yet.

> Have you tried to use Nginx + Phusion Passenger?

No. I take it that you are recommending it. Thank you. I'll have to see how it works with Docker containers.

**Comment by dr-dimitru** [comment]
Okay, keep this thread updated please.
Take a look on this Docker-related article - https://github.com/VeliovGroup/Meteor-Files/wiki/MeteorUp-(MUP)-Usage

**Comment by RavDanny** [comment]
Ok. Thanks

**Comment by RavDanny** [comment]
Actually, I'm having a another significant file upload problem with my current Nginx configuration (which includes your modifications). While uploading on one screen, I'm unable to use my app on another window (or on another computer, for that matter). I wasn't sure if it was an issue that would go away upon deployment, or if it is a problem with the Nginx configuration requiring modification. I'd be happy for your feedback.

**Comment by dr-dimitru** [comment]
Hello @RavDanny ,

Have you seen those threads?:
 - https://forums.meteor.com/t/connecting-to-websocket-returns-400-prod-proxy/39029
 - https://github.com/VeliovGroup/Meteor-Files/issues/475


Let me know if it was helpful

**Comment by dr-dimitru** [comment]
Hey @RavDanny ,

Haven't heard from you for a while.
Have you managed those issues?

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.

**Comment by RavDanny** [comment]
Hi @dr-dimitru,
Sorry. I was away on leave. I'm only working on this project intermittently, so I haven't been able to progress with this. I will let you know if/when I solve it.
Thanks

**Comment by dr-dimitru** [comment]
@RavDanny sure, just reopen it once you will be back.
*I'm cleaning up repository before big release.*

**Comment by RavDanny** [comment]
Hi @dr-dimitru,
Funny thing. When I changed the upload transport back from `http` to `ddp` it seemed to solve the problem. It allowed me to load the app in a different window. Also when I aborted an upload it didn't give me lots of `POST... 500 (Internal Server Error)` messages in the console the way `http` did. It also uploaded 4x faster (on my slowish internet connection). Should be the opposite!

I suppose it suggests that my nginx is not configured properly for `http` uploads?
Any thoughts?

**Comment by dr-dimitru** [comment]
Hello @RavDanny ,

> I suppose it suggests that my nginx is not configured properly for http uploads?
> Any thoughts?

I never used any special Nginx settings for the file upload. But it really depends from how server manages sockets, Linux version, virtualization and etc., too many variables.

DDP may be faster and more stable in some cases, as it keeps connection open, and there is no need to exchange first byte and do handshake for every request.

 1. Have you tried `epoll`, `http2`, `deferred`, `reuseport` options and its combinations?
 2. Where do you host your app?
